### ISSUE TITLE
Segmentation module error

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#102]
I've been getting the following error when trying to run the segmentation module using YeaZ and the CellACDC tracker:

Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 558, in launchSegm
    self.segmWin.main()
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 990, in main
    posData.loadOtherFiles(
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\load.py", line 349, in loadOtherFiles
    endName = filename[len(self.basename):]
AttributeError: 'loadData' object has no attribute 'basename'

I can still segment one frame at a time via the GUI, but the module that lets me segment many positions at once gives me this.

Windows 10
Python 3.9.6
Version: ACDC v1.2.4rc32

**Comment by ElpadoCan** [comment]
Hi Jordan, I released `v1.2.4rc33` which has a fix for this issue.

Sorry about that. We are working on having automated tests to catch as many bugs as possible before releasing a new version. This would have been definitely detected with automated tests.

Anyway, update with `pip install --upgrade cellacdc` and let me know if it works! Thanks!

**Comment by jordanyx** [comment]
It's working now, thanks!
