### ISSUE TITLE
Skip positions without complete seg/track when resaving on multiple experiments/positions

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#115]
When using the "Compute measurements for one or more experiments" utility, I sometimes accidentally try to save metrics on positions that don't have proper segmentation/tracking, and I get an error like the below. It would be helpful if there were an option to resave the GUI outputs only on positions with completed segmentation/tracking. In the meantime, I have to manually check which positions are able to be resaved.

Perhaps more broadly, it would be useful if there was a quick way to reference which positions have been previously saved or run through complete seg/track/mother-bud-division analysis without having to open the Images folder in File Explorer.

"
C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\core\fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py:641: RuntimeWarning: Mean of empty slice.
  bkgr_val = ROI_bkgrData.mean()
====================
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\utils\compute.py", line 248, in workerCritical
    raise error
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 27, in run
    func(self)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 355, in run
    acdc_df = self.mainWin.gui.saveDataWorker.addMetrics_acdc_df(
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 649, in addMetrics_acdc_df
    bkgr_val = np.quantile(ROI_bkgrData, q=0.75)
  File "<__array_function__ internals>", line 5, in quantile
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 3979, in quantile
    return _quantile_unchecked(
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 3986, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 3564, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 4109, in _quantile_ureduce_func
    x_below = take(ap, indices_below, axis=0)
  File "<__array_function__ internals>", line 5, in take
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
"

**Comment by ElpadoCan** [comment]
Hi Jordan, you are right, the widget that allows you to select the Positions doesn't provide any information about the status of the Position. I will add the information about last tracked frame and last annoated frame for each Position. 

For the error it looks like the `ROI_bkgrData` is empty and one possible explanation is that you selected a 0-width or 0-height background ROI in the data prep step? Because I know that at some point I made the background ROI that cannot be squeezed down to 0 width or 0 height but I don't remember if I released that feature or not. In any case could you share the Position that gives that error? Because it could be a bug not related to the fact that you didn't segment/tracked this Position, thanks! 

In any case, I will add that it skips Positions with errors and it shows you a report at the end of which Positions where skipped and why.

**Comment by ElpadoCan** [comment]
Also, I realised now that I forgot to add the combined metrics calculation to the utility.... I will do that
