### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by dfgdgdfgd** [SchmollerLab/Cell_ACDC#166]
Hi ElpadoCan,

first, thanks for your work!
Unfortunatly i can not try it, since i encountered 2 consecutive errors when starting the segmentation module (seems to be independently from the choosen model, but i tried until now just Stardist and Cellpose):

1. Error:
Appears, when i choose Stardist or Cellpose. Installation of both works fine (automatically and manually!), but after starting the segmentation task, i get the following warnings:

Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 813, in launchSegm
    self.segmWin.main()
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 1063, in main
    self.startSegmWorker()
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 1180, in startSegmWorker
    worker = segmWorker(img_path, self)
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 87, in __init__
    self.track_params = mainWin.track_params
AttributeError: 'segmWin' object has no attribute 'track_params'

2. Error:
After abort and restart, ACDC is not starting, instead i get the following warnings:

Importing modules...
Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\acdc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programme\Anaconda3\envs\acdc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programme\Anaconda3\envs\acdc\Scripts\acdc.exe\__main__.py", line 4, in <module>
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 82, in <module>
    from cellacdc import (
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\dataPrep.py", line 40, in <module>
    from . import load, prompts, apps, core, myutils, widgets
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\load.py", line 5, in <module>
    import cv2
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cv2\__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2

Any idea??

Thanks a lot
best
Mario

 - Python version: Python 3.9
 - OS: Windows 10
 - Cell-ACDC Version 1.2.4rc43

**Comment by ElpadoCan** [comment]
Hi Mario, I'm sorry to hear you are having issues. 

So for the first error, I released a new version `v1.2.4rc44` which should have a fix for that (huge thanks for reporting this, by the way). 

To update Cell-ACDC to the latest version, please activate the `acdc` environment and then run the command `pip install --upgrade cellacdc`. 

For the second error instead, I fear that some package somehow broke OpenCV installation. You should be able to fix it with the following commands:

1. Activate the `acdc` environment
2. Run the command `pip uninstall opencv-python` (ignore the message if it says not found)
3. Run the command `pip uninstall opencv-python-headless`
4. Run the command `pip install opencv-python-headless`

This should uninstall and reinstall OpenCV. Let me know if it works, thanks! 

Cheers,
Francesco

**Comment by dfgdgdfgd** [comment]
Dear Francesco,

thank you very much for the fast response!!
Now it works.

You did a great job, it´s a really powerful software suite!

Best
Mario

**Comment by dfgdgdfgd** [comment]
Hi Francesco,

unfortunatly i encontered the following issue when trying to segment an 2D tiff with Cellpose:

Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 871, in launchSegm
    self.segmWin.main()
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 876, in main
    filenames = posData.segmInfo_df.index.get_level_values(0).unique()
AttributeError: 'NoneType' object has no attribute 'index'

Thanks again!
Best
Mario

**Comment by dfgdgdfgd** [comment]
wow, that was fast... ;)

Thanks a lot, it works!

Best
Mario

**Comment by ElpadoCan** [comment]
No problem, I'm happy you like it and hopefully it will also be useful to your work! 

And do not hesitate to contact us for issues or ideas on how to improve the experience! 

Cheers,
Francesco
