### ISSUE TITLE
Error when creating segm.npz from .tif

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#172]
... I encountered a new issue with a 3D masks.tiff i segmented directly in Cellpose and converted using your utility to  _segm.npz.
I imported the _segm.npz file into the GUI, tried to save it and received the following issue:

==============================
Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 1122, in run
    acdc_df = self.addMetrics_acdc_df(
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 664, in addMetrics_acdc_df
    metrics_values[bkgr_key][i] = np.quantile(
  File "<__array_function__ internals>", line 180, in quantile
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 4412, in quantile
    return _quantile_unchecked(
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\lib\function_base.py", line 4704, in _quantile
    previous = np.take(arr, previous_indexes, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "D:\Programme\Anaconda3\envs\acdc\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
******************************

Should i send you the 3D file? 

Thanks and best
Mario

![image](https://user-images.githubusercontent.com/116281469/197620299-6f7b7fbb-b022-445e-90d1-a27a36dade9d.png)

_Originally posted by @dfgdgdfgd in https://github.com/SchmollerLab/Cell_ACDC/issues/169#issuecomment-1289565595_

**Comment by ElpadoCan** [comment]
Closing because created by mistake
