### ISSUE TITLE
Error in function _openFolder

### ISSUE THREAD

**Issue by GalHanuka** [SchmollerLab/Cell_ACDC#189]
### Description:

I am trying to load the images (tif file), ang there is an eror. 

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\galus\anaconda3\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 54, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\galus\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 17037, in _openFolder
    ch_name_selector.get_available_channels(filenames, exp_path)
  File "C:\Users\galus\anaconda3\envs\acdc\lib\site-packages\cellacdc\prompts.py", line 128, in get_available_channels
    isBasenamePresent = myutils.checkDataIntegrity(filenames, images_path)
  File "C:\Users\galus\anaconda3\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 386, in checkDataIntegrity
    char = filenames[0][:2]
IndexError: list index out of range
```

**Comment by GalHanuka** [comment]
[2022-11-14_12-31-34_main_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002577/2022-11-14_12-31-34_main_stdout.log)
[2022-11-14_12-50-24_main_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002578/2022-11-14_12-50-24_main_stdout.log)
[2022-11-14_13-24-14_dataPrep_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002579/2022-11-14_13-24-14_dataPrep_stdout.log)
[2022-11-14_13-25-05_dataPrep_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002580/2022-11-14_13-25-05_dataPrep_stdout.log)
[2022-11-14_13-27-41_dataPrep_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002582/2022-11-14_13-27-41_dataPrep_stdout.log)
[2022-11-14_13-27-53_dataStruct_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002583/2022-11-14_13-27-53_dataStruct_stdout.log)
[2022-11-14_13-28-21_dataPrep_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002584/2022-11-14_13-28-21_dataPrep_stdout.log)
[2022-11-14_13-28-51_main_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002585/2022-11-14_13-28-51_main_stdout.log)
[2022-11-14_13-30-01_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10002586/2022-11-14_13-30-01_gui_stdout.log)

**Comment by ElpadoCan** [comment]
Hi @GalHanuka, 

I'm sorry to hear you are facing issues, but we'll fix them.

For what I can see from the log files you tried the following:

1. You run module 0. and you choose "Multiple files, one for each time-point"
2. You tried the Bioformats module of module 0. and you got an error for `javabridge`
3. You get the error in module 3. when you try to open the files in the GUI

If this is correct, let me comment on these operations:

1. The names of your files for this particular module are incorrect. Your file is called `t04xy1c1.tif`, but the valid pattern is `position_channel_timepoint.tif`, so given your filename, I would guess you could rename the files as `xy1_c1_04.tif` where `xy1` is the position, `c1` is the channel name, and `04` is the frame number. If you have many files to rename I can think of also allowing the pattern that you already have. 
2. When you try Bioformats the first time it needs to install `javabridge`, because unfortunately Bio-Formats is written in Java and Python needs a package to run Java scripts. How did that installation go? 
3. To fix this error Cell-ACDC needs the right data structure so first we need to solve the issues 1. and/or 2.

Now, the easiest for me to debug this is to have a sample of your data. You could send it to me via Google Drive (or whatever another service you prefer) at my email padovaf@tcd.ie. Please, add a description of how is your data currently structured. Also, do you have the raw microscopy file?

Let me know if you can share a sample of the data, thanks! 

Cheers,
Francesco
