### ISSUE TITLE
failure to install javabridge

### ISSUE THREAD

**Issue by jacobmhkim** [SchmollerLab/Cell_ACDC#19]
**Describe the bug**
I got a message saying "Cell-ACDC is going to download and install javabridge". It was able to download it, but failed during installation

**To Reproduce**
1. Start ACDC
2. Click on Module 0
3. Press OK when the message saying it's going to download javabridge
4. See error:
"Traceback (most recent call last):
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\dataStruct.py", line 830, in __init__
    import javabridge
ModuleNotFoundError: No module named 'javabridge'
Traceback (most recent call last):
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\dataStruct.py", line 830, in __init__
    import javabridge
ModuleNotFoundError: No module named 'javabridge'
======================================
Collecting git+https://github.com/SchmollerLab/python-javabridge-windows
  Cloning https://github.com/SchmollerLab/python-javabridge-windows to c:\users\jacob\appdata\local\temp\pip-req-build-7ut378wk
  Running command git clone -q https://github.com/SchmollerLab/python-javabridge-windows 'C:\Users\Jacob\AppData\Local\Temp\pip-req-build-7ut378wk'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/SchmollerLab/python-javabridge-windows 'C:\Users\Jacob\AppData\Local\Temp\pip-req-build-7ut378wk'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Traceback (most recent call last):
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\dataStruct.py", line 830, in __init__
    import javabridge
ModuleNotFoundError: No module named 'javabridge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 381, in _showDataStructWin
    self.dataStructWin = dataStruct.createDataStructWin(parent=self)
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\dataStruct.py", line 896, in __init__
    myutils.install_javabridge()
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 192, in install_javabridge
    subprocess.check_call(
  File "C:\Users\Jacob\miniconda3\envs\acdc\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Jacob\\miniconda3\\envs\\acdc\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/SchmollerLab/python-javabridge-windows']' returned non-zero exit status 1."

**Expected behavior**
I expected the installation to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/10964296/160174248-f022746f-cde5-420e-b44e-24a9565051e0.png)

**Desktop (please complete the following information):**
 - Python version: [e.g. Python 3.9]
 - OS: [e.g. Windows 10]
 - Cell-ACDC Version [e.g. v1.2.4, you can find this from the menu "Help-->About Cell-ACDC" on the main Launcher]

**Additional context**

**Comment by jacobmhkim** [comment]
Update: installed Git for Windows via website and ran cell acdc through again. got a new error:
![image](https://user-images.githubusercontent.com/10964296/160177945-f8896717-33a0-46a5-b29e-8309055a2724.png)

**Comment by jacobmhkim** [comment]
Thanks! It worked!
