### ISSUE TITLE
Possible bug when deleting objects including unvisited frames

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#210]
### Description:

Possible bug

### Terminal output:

```Shell
Traceback (most recent call last):
File "C:\Users\yagya.chadha\Desktop\Yagya\segmentation\Yeast_segm_cca-main\Yeast_ACDC\cellacdc\__init__.py", line 102, in inner_function
result = func(self, *args)
File "C:\Users\yagya.chadha\Desktop\Yagya\segmentation\Yeast_segm_cca-main\Yeast_ACDC\cellacdc\gui.py", line 4328, in gui_mousePressEventImg2
lab = posData.segm_data[i]
IndexError: index 440 is out of bounds for axis 0 with size 440
```

**Comment by ElpadoCan** [comment]
This happens when segm SizeT is less than SizeT

**Comment by ElpadoCan** [comment]
Closed by [this](https://github.com/SchmollerLab/Cell_ACDC/commit/bec65dcdc14cbba4830bb38fa5872413b6c29e8d) commit
