### ISSUE TITLE
Sequential relabel error

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#23]
**Describe the bug**
Sequential relabel function crashes.

**To Reproduce**
1. Open a movie in the GUI.
2. Ctrl-L or use menu option to select sequential relabel function.
3. Get error below:

_Relabelling process started...
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 122, in inner_function
    result = func(self, *args)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 8022, in workerCritical
    raise error
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 23, in run
    func(self)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 240, in run
    current_lab = self.get_2Dlab(posData.lab).copy()
AttributeError: 'relabelSequentialWorker' object has no attribute 'get_2Dlab'
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 122, in inner_function
    result = func(self, *args)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 8022, in workerCritical
    raise error
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 23, in run
    func(self)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 240, in run
    current_lab = self.get_2Dlab(posData.lab).copy()
AttributeError: 'relabelSequentialWorker' object has no attribute 'get_2Dlab'_

**Desktop (please complete the following information):**
 - Python version: 3.9.7
 - OS: Windows 10
 - Cell-ACDC Version v1.2.4rc11

**Additional context**
This is my first time trying the function. It's being done on data that has already been tracked, in case that makes a difference.

**Comment by jordanyx** [comment]
Works great now, thanks!
