### ISSUE TITLE
"Plus" icon for custom annotations is broken

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#249]
### Description:

I don't know why, but I can't set up any annotations with the "plus" symbol as an icon :D

### Way to reproduce:

1. Try to make custom annotation with "plus" icon;
2. Nothing happens;
3. Cry.

### Terminal output:

```Shell
Importing modules...
Importing GUI modules...
Launching application...
****************************************
Traceback (most recent call last):
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 504, in read_version
    version = get_version(root='..', relative_to=__file__)
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\setuptools_scm\__init__.py", line 149, in get_version
    _version_missing(config)
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\setuptools_scm\__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

----------------------------------------
[WARNING]: Cell-ACDC could not determine the current version. See details above.
========================================
Requirement already satisfied: setuptools-scm in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (7.0.5)
Requirement already satisfied: typing-extensions in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (from setuptools-scm) (4.4.0)
Requirement already satisfied: tomli>=1.0.0 in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (from setuptools-scm) (2.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (from setuptools-scm) (21.3)
Requirement already satisfied: setuptools in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (from setuptools-scm) (65.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\myermolaie\miniconda3\envs\acdc\lib\site-packages (from packaging>=20.0->setuptools-scm) (3.0.9)
****************************************
Traceback (most recent call last):
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\cellacdc\myutils.py", line 504, in read_version
    version = get_version(root='..', relative_to=__file__)
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\setuptools_scm\__init__.py", line 149, in get_version
    _version_missing(config)
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\setuptools_scm\__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

----------------------------------------
[WARNING]: Cell-ACDC could not determine the current version. See details above.
========================================
**********************************************
Welcome to Cell-ACDC v1.2.4rc58!
**********************************************
----------------------------------------------
NOTE: If application is not visible, it is probably minimized
or behind some other open window.
----------------------------------------------
Opening GUI...
Initializing GUI v1.2.4rc58...
Opening FOLDER "None"
Loading from Y:/Max/EXP3/Clean positions/Position_1
Lazy loader paused.
Using .npz aligned file (Y:/Max/EXP3/Clean positions\Position_1\Images\xy01_s01_gray_aligned.npz)...
Reading gray channel metadata...
Segmentation filename: Y:/Max/EXP3/Clean positions\Position_1\Images\xy01_s01_segm_1.npz
Closing lazy loader...
Loading Position_1\Images\xy01_s01_gray_aligned.npz...
Loaded paths:
Segmentation file name: xy01_s01_segm_1.npz
ACDC output file name xy01_s01_acdc_output_1.csv
Full dataset shape = Not Loaded
Loaded dataset shape = (121, 765, 709)
Number of frames = 121
Number of z-slices per frame = 1
Counting total number of segmented objects...
100%|██████████████████████████████████████████████████████████████| 97/97 [00:00<00:00, 926.30it/s]
Creating 4 axes items...
100%|████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 444.11it/s]
Adding 4 axes items...
100%|████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 285.59it/s]
Autosaving worker started.
Initializing measurements...
Loading fluorescence image data from "Y:/Max/EXP3/Clean positions\Position_1\Images\xy01_s01_red_aligned.npz"...
Loading saved custom annotations...
Basename: xy01_s01_ || Segmented channel: gray_aligned || Segmentation file name: segm_1.npz || Position_1
Loading saved custom annotations...
Traceback (most recent call last):
  File "C:\Users\myermolaie\Miniconda3\envs\acdc\lib\site-packages\cellacdc\apps.py", line 820, in closeEvent
    self.symbol = re.findall(r"\'(\w+)\'", symbol)[0]
IndexError: list index out of range
```

### Version information:

```Shell
>>> import sys; print(sys.version)
3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.19045-SP0
>>> import cellacdc; print(f'Cell-ACDC version: {cellacdc.__version__}')
Cell-ACDC version: 1.2.4rc58
```

**Comment by ElpadoCan** [comment]
Hi Max, I just released `v1.2.4rc59` with a fix for this issue.

To update, activate the acdc environment and then run the command `pip install --upgrade cellacdc`. Let me know if it works now, thanks! 

Cheers,
Francesco
