### ISSUE TITLE
NetworkX error when greedily shuffling colormap

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#323]
### Description:

NetworkX error when greedily shuffling colormap

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 16911, in greedyShuffleCmap
    greedy_lut = colors.get_greedy_lut(self.currentLab2D, lut)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\colors.py", line 168, in get_greedy_lut
    G = nx.from_numpy_matrix(adj_M)
AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 16911, in greedyShuffleCmap
    greedy_lut = colors.get_greedy_lut(self.currentLab2D, lut)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\colors.py", line 168, in get_greedy_lut
    G = nx.from_numpy_matrix(adj_M)
AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'
```

**Comment by ElpadoCan** [comment]
Fix: replace `from_numpy_matrix` with `from_numpy_array`
