### ISSUE TITLE
Error when running trackpy with default params

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#327]
### Description:

When I try to run trackpy in the Segmentation module, I get an error.

### Way to reproduce:

Schmoller lab file, timelapse, z=1, only phase contrast channel,
let me know if I should send the data

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\__init__.py", line 152, in inner_function
    result = func(self, *args)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\segm.py", line 1301, in workerCritical
    raise error
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\segm.py", line 100, in run
    self._run()
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\segm.py", line 401, in _run
    tracked_stack = self.tracker.track(
TypeError: track() got an unexpected keyword argument 'image'
```

**Comment by ElpadoCan** [comment]
Hi Beno, 

Thanks for reporting this. I fixed it now.

To get the fix, pull the latest version with `git pull`, when you have time. Let me know if it works, thanks! 

Cheers,
Francesco

**Comment by Beno71** [comment]
Nice, seems to work well now. I had some other error with importing numba, I'll attach it at the bottom. But it was solved with resetting the environment (which was anyways due for some time). 
`Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\__main__.py", line 1223, in launchSegm
    self.segmWin.main()
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\segm.py", line 1129, in main
    self.tracker, self.track_params = myutils.import_tracker(
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\myutils.py", line 1764, in import_tracker
    trackerModule = import_module(trackerModuleName)
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\trackers\trackpy\__init__.py", line 2, in <module>
    import trackpy
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\trackpy\__init__.py", line 11, in <module>
    from trackpy.api import *
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\trackpy\api.py", line 12, in <module>
    from .linking import (link, link_df, link_iter, link_df_iter,
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\trackpy\linking\__init__.py", line 1, in <module>
    from .linking import (link, link_df, link_iter, link_df_iter,
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\trackpy\linking\linking.py", line 9, in <module>
    from ..try_numba import NUMBA_AVAILABLE
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\trackpy\try_numba.py", line 20, in <module>
    import numba
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception`
