### ISSUE TITLE
Non-critical error when launching GUI

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#328]
### Description:

When opening the GUI without custom annotations performed before, I get an error in the step "Loading saved custom annotations..."

### Way to reproduce:

Open GUI of timelapse file after performing segmentation and tracking with the seg module

### Terminal output:

```Shell
Loading saved custom annotations...
2023-05-10 12:33:07,931 [INFO] Loading saved custom annotations...
Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\load.py", line 62, in read_json
    json_data = json.load(file)
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 11 (char 12)

2023-05-10 12:33:07,970 [INFO] Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\load.py", line 62, in read_json
    json_data = json.load(file)
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\mairhoermann\Anaconda3\envs\acdc_temp\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 11 (char 12)
```

**Comment by ElpadoCan** [comment]
Hi Beno, we already fixed this but now you have a corrupted file that you need to delete manually. After deletion you should not see this error anymore.

Please delete the file `Cell_ACDC/cellacdc/temp/custom_annotations.json`

This file holds all the custom annotations that have been created in the past to allow you loading a custom annotation that you setup in a different position. I recently found that this file can be corrupted and I fixed it so it should not be corrupted anymore in the future (after you delete it). Let me know if it works thanks!

**Comment by Beno71** [comment]
Great, that worked!
