### ISSUE TITLE
Type error when using trackpy from the Tracking menu in GUI

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#330]
### Description:

When I want to start "Tracking on multiple frames... (Alt+Shift+T)" with trackpy, there's an error occuring regarding my preselected settings for the tracker.

### Terminal output:

```Shell
Saved data until frame number 37  <--- saved my data
Importing trackpy tracker...  <--- decided to retrack from frame 38 to end, error appears when asked for tracker params
Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\apps.py", line 9893, in loadLastSelection
    argWidget.valueSetter(widget, val)
TypeError: setText(self, a0: str): argument 2 has unexpected type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\apps.py", line 9895, in loadLastSelection
    argWidget.valueSetter(widget, int(val))
TypeError: setText(self, a0: str): argument 2 has unexpected type 'int'
```

**Comment by Beno71** [comment]
Edit: I also get the error when starting trackpy from the Segmentation Module
