### ISSUE TITLE
Errors while adding resizable rectangle to ignore IDs in frames when the later frames have already been visited.

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#336]
### Description:

Errors while adding resizable rectangle to ignore IDs in frames when the later frames have already been visited.

### Way to reproduce:

1. Error: Add resizable rectangle to ignore IDs in a frame you have already visited. While moving through the frames back to the last edited one, after a few frames this error will occur. 

2. Error: Trying to save data after 1. error occurred. 

3. Error: After 1. error occurred, if  try to move further this error will be raised, followed by the first one again.

### Terminal output:

```Shell
First error:
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 156, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 17970, in updateAllImages
    self.setAllTextAnnotations()
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 17922, in setAllTextAnnotations
    self.textAnnot[0].setAnnotations(
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\annotate.py", line 481, in setAnnotations
    pos = (int(xc), int(yc))
ValueError: cannot convert float NaN to integer


Second error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 156, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14450, in store_data
    xx_centroid[i] = int(self.getObjCentroid(obj.centroid)[1])
ValueError: cannot convert float NaN to integer


3. Error:
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 156, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14450, in store_data
    xx_centroid[i] = int(self.getObjCentroid(obj.centroid)[1])
ValueError: cannot convert float NaN to integer
```

### Version information:

```Shell
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Initialising...
Cell-ACDC version: 1.3.1.dev0+ge675ed7.d20230525
```

**Comment by ElpadoCan** [comment]
Hi Timon, thanks for reporting this! 

I just fixed it. To get the fix open the terminal, go to the Cell_ACDC folder and run `git pull`. If you have local changes you first need to run `git stash`, then you run the `git pull` and then you can get your changes back with `git stash pop`.

Let me know if it works, thanks!
