### ISSUE TITLE
"Cells in "S/G2/M" disappeared" warning about disapeareance of a cell idex which does not exist

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#338]
### Description:

During Cell Cycle Analysis, "Cells in "S/G2/M" disappeared" warning will show, referring to the disappearance of a cell index which does not exist. Choosing "Yes" causes the error and you cannot proceed to the next frame.

### Way to reproduce:

See description, maybe has to do with exclusion ROIs, as I used them but they didn't work properly (new cells IDs would still show up) and ended up manually deleting them

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 156, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14662, in attempt_auto_cca
    notEnoughG1Cells, proceed = self.autoCca_df(
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14822, in autoCca_df
    abort, automaticallyDividedIDs = self.checkScellsGone()
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14623, in checkScellsGone
    prev_cca_df = prev_acdc_df[self.cca_df_colnames].copy()
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\frame.py", line 3766, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 5935, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['cell_cycle_stage', 'generation_num', 'relative_ID', 'relationship',\n       'emerg_frame_i', 'division_frame_i', 'is_history_known',\n       'corrected_assignment', 'will_divide'],\n      dtype='object')] are in the [columns]"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 54

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 156, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14662, in attempt_auto_cca
    notEnoughG1Cells, proceed = self.autoCca_df(
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14822, in autoCca_df
    abort, automaticallyDividedIDs = self.checkScellsGone()
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 14651, in checkScellsGone
    relID = prev_cca_df.at[IDgone, 'relative_ID']
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexing.py", line 2412, in __getitem__
    return super().__getitem__(key)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexing.py", line 2364, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\frame.py", line 3886, in _get_value
    row = self.index.get_loc(index)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 54
```

### Version information:

```Shell
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Initialising...
Cell-ACDC version: 1.3.1.dev13+g8ac8b18
```

**Comment by Teranis** [comment]
[FP_ER_FPY004-1_SCD-3h_SCGE-12h-01_s08_acdc_output.csv](https://github.com/SchmollerLab/Cell_ACDC/files/11576718/FP_ER_FPY004-1_SCD-3h_SCGE-12h-01_s08_acdc_output.csv)
Here the acdc_output.cvs. The error occurred on frame 66.
