### ISSUE TITLE
DeepSea tracker min_size keyword error

### ISSUE THREAD

**Issue by zsdqui** [SchmollerLab/Cell_ACDC#350]
### Description:

When trying to track multiple frames using DeepSea, I get an error that track_cells() got unexpected keyword "min_size"
[2023-06-15_08-51-30_acdc_gui_caa78299-5f65-4b24-bf22-97dd24ce95cb_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/11759719/2023-06-15_08-51-30_acdc_gui_caa78299-5f65-4b24-bf22-97dd24ce95cb_stdout.log)

### Way to reproduce:

1) Convert .tiff using step 0 converter for both images and masks
2) Prep data in step 1 (no cropping)
3) Start GUI and place in segmentation/tracker mode
4) Select tracking-multiple frames -> Deep sea -> I adjusted min size as 3, no GPU 

### (Optional) Link to data to reproduce error:

shared privately

### Terminal output:

```Shell
Importing DeepSea tracker...
Tracking process started...
  0%|                                                                         | 0/7 [00:00<?, ?it/s]Resizing objects...
100%|████████████████████████████████████████████████████████████████| 7/7 [42:57<00:00, 368.15s/it]
Image data is not required by this tracker, ignoring it...
Traceback (most recent call last):
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 1200, in run
    tracked_video = self.tracker.track(
  File "C:\Users\zsdqu\miniconda3\envs\acdc\Lib\site-packages\cellacdc\trackers\DeepSea\DeepSea_tracker.py", line 88, in track
    result = track_cells(
TypeError: track_cells() got an unexpected keyword argument 'min_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 154, in inner_function
    result = func(self, *args)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 12500, in workerCritical
    raise error
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 38, in run
    func(self)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 1209, in run
    tracked_video = self.tracker.track(
TypeError: track() missing 1 required positional argument: 'image'
Traceback (most recent call last):
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 1200, in run
    tracked_video = self.tracker.track(
  File "C:\Users\zsdqu\miniconda3\envs\acdc\Lib\site-packages\cellacdc\trackers\DeepSea\DeepSea_tracker.py", line 88, in track
    result = track_cells(
TypeError: track_cells() got an unexpected keyword argument 'min_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 154, in inner_function
    result = func(self, *args)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 12500, in workerCritical
    raise error
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 38, in run
    func(self)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 1209, in run
    tracked_video = self.tracker.track(
TypeError: track() missing 1 required positional argument: 'image'
```

### Version information:

```Shell
>>> import sys; print(sys.version)
3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.platform())
Windows-10-10.0.22621-SP0
>>> import cellacdc; print(f'Cell-ACDC version: {cellacdc.__version__}') 
Cell-ACDC version: 1.3.0
```

**Comment by ElpadoCan** [comment]
Hi @zsdqui,

You are absolutely right, DeepSea was published to PyPi without merging my Pull Requests first (which adds the `min_size`  parameter). You can see my PR [here](https://github.com/abzargar/DeepSea/pull/2).

@abzargar would you be able to help here? Could you please review the PR, merge it and publish a new version of DeepSea? Thanks!

@zsdqui in the meantime I can publish Cell-ACDC without the `min_size` keyword, the default is 20 pixels (meaning that objects with less than 20 pixels in area are removed). Would that work for you? Thank you for your patience!

Best,
Francesco

**Comment by abzargar** [comment]
Thank you for your email. I just mergered your request.

Sincerely,


Abolfazl Zargari


Ph.D. student and research assistant

Electrical and Computer Engineering Department

The University of California, Santa Cruz
Email: ***@***.***

**Comment by zsdqui** [comment]
thanks for the quick updates! - I am now getting the following error - let me know if I should open a new issue

Traceback (most recent call last):
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 154, in inner_function
    result = func(self, *args)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 12500, in workerCritical
    raise error
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 38, in run
    func(self)
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 1200, in run
    tracked_video = self.tracker.track(
  File "C:\Users\zsdqu\miniconda3\envs\acdc\Lib\site-packages\cellacdc\trackers\DeepSea\DeepSea_tracker.py", line 88, in track
    result = track_cells(
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\deepsea\utils.py", line 559, in track_cells
    tracked_imgs.append(add_labels_to_image(img_curr, labels_curr, centroids_curr))
  File "C:\Users\zsdqu\miniconda3\envs\acdc\lib\site-packages\deepsea\utils.py", line 160, in add_labels_to_image
    img = cv2.putText(img, label, tuple(point), cv2.FONT_HERSHEY_SIMPLEX, fontScale, color, thickness);
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'putText'
> Overload resolution failed:
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type

**Comment by ElpadoCan** [comment]
Hi @zsdqui, I just tried with some test data and it worked, so I'm guessing your error is caused by the fact that you have data that is not 8-bit (I think). DeepSea uses openCV in some places and openCV can work only with 8-bit images so we need to add a conversion step before calling openCV. 

I know you sent me your data so I will run some tests and I will let you know soon, thank you for your patience and have a nice weekend!

Best,
Francesco

**Comment by abzargar** [comment]
Can you share some of your data samples with me to see what type of cell
images you are using? I also want to try it to see what the problem is.

Sincerely,


Abolfazl Zargari


Ph.D. student and research assistant

Electrical and Computer Engineering Department

The University of California, Santa Cruz
Email: ***@***.***

**Comment by zsdqui** [comment]
Just shared with you a sample of the tiffs for the images and segmentation masks @abzargar

**Comment by abzargar** [comment]
So sorry for the late reply. I missed your message and I was in vacation.
Actually the images you shared are not organized and prepared in a good
format. In most of them there is big white circle. What is that? Whay don't
you have a folders of images that you want to segment? I don't know what
images you are giving to the DeepSea model and how. This format of data is
not applicable. Please export your raw data into images first (preferably
in png format as you see in DeepSea dataset) and try again. You can also
share it with me as well to test.


Sincerely,


Abolfazl Zargari


Ph.D. student and research assistant

Electrical and Computer Engineering Department

The University of California, Santa Cruz
Email: ***@***.***

**Comment by ElpadoCan** [comment]
Hi @abzargar I was also "fooled" by the white circle but that is only because they are 32 bit float images that are not displayed well by Fiji. If you open them in python and display them with matplotlib they will look correct.
