### ISSUE TITLE
Error when trying to reassign a bud 

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#368]
### Description:

Error when trying to reassign a bud 

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 57

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\__init__.py", line 243, in inner_function
    result = func(self, *args)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 6457, in gui_mouseReleaseEventImg1
    self.assignBudMoth()
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 8777, in assignBudMoth
    eligible = self.checkMothEligibility(budID, new_mothID)
  File "C:\Users\SchmollerLab\Cell_ACDC\cellacdc\gui.py", line 8627, in checkMothEligibility
    is_still_bud = cca_df_i.at[budID, 'relationship'] == 'bud'
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexing.py", line 2412, in __getitem__
    return super().__getitem__(key)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexing.py", line 2364, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\frame.py", line 3886, in _get_value
    row = self.index.get_loc(index)
  File "C:\Users\SchmollerLab\.virtualenvs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 57
```

**Comment by Teranis** [comment]
Error happens when trying to re-assign a bud that will disappear in of the future already visited frames. 

The function `gui.checkMothEligibility` should break the for loop checking future frames if the bud does not exist anymore.

Proposed fix:

```
    def checkMothEligibility(self, budID, new_mothID):
        """
        Check that the new mother is in G1 for the entire life of the bud
        and that the G1 duration is > than 1 frame
        """
        posData = self.data[self.pos_i]
        eligible = True

        G1_duration = 0
        # Check future frames
        for i in range(posData.frame_i, posData.SizeT):
            cca_df_i = self.get_cca_df(frame_i=i, return_df=True)

            if cca_df_i is None:
                # ith frame was not visited yet
                break
            
            if budID not in cca_df_i.index:
                # Bud disappeared
                break
```
