### ISSUE TITLE
Error by deleting cells 

### ISSUE THREAD

**Issue by AlissaAFinster** [SchmollerLab/Cell_ACDC#390]
### Description:

When I want to delete a cell by clicking in the middle of my mouse, insert the number & submit, it doesn't work and gives me this error. This might have happened due to the multiple-deletion-update.

### Terminal output:

```Shell
Traceback (most recent call last):
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\__init__.py", line 316, in inner_function
result = func(self, *args)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 4590, in gui_mousePressEventImg2
delID_mask = self.deleteIDmiddleClick(
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 19563, in deleteIDmiddleClick
self.clearObjContour(ID=delID, ax=0)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 19430, in clearObjContour
if ID > 0:
TypeError: '>' not supported between instances of 'list' and 'int'
```

### Version information:

```Shell
'import' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ElpadoCan** [comment]
Hi Alissa, you are right I forgot to test deleting a single ID with the mouse button. It should be working now, let me know thanks!
