### ISSUE TITLE
Error saving standard metrics data

### ISSUE THREAD

**Issue by AlissaAFinster** [SchmollerLab/Cell_ACDC#395]
### Description:

When I want to save my result WITH all standard metrics, it gives me this error. 

### Terminal output:

```Shell
==============================
Traceback (most recent call last):
  File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 699, in run
    acdc_df = self.addMetrics_acdc_df(
  File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 390, in addMetrics_acdc_df
    autoBkgr_masks = measurements.get_autoBkgr_mask(
  File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\measurements.py", line 797, in get_autoBkgr_mask
    autoBkgr_mask = _mask_0valued_pixels_from_alignment(
  File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\measurements.py", line 1101, in _mask_0valued_pixels_from_alignment
    is_cropped = int(posData.dataPrep_ROIcoords.at['cropped', 'value'])
  File "C:\Users\alissa.finster\Miniconda3\envs\acdc\lib\site-packages\pandas\core\indexing.py", line 2419, in __getitem__
    return super().__getitem__(key)
  File "C:\Users\alissa.finster\Miniconda3\envs\acdc\lib\site-packages\pandas\core\indexing.py", line 2371, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\Users\alissa.finster\Miniconda3\envs\acdc\lib\site-packages\pandas\core\frame.py", line 3882, in _get_value
    loc = engine.get_loc(index)
  File "pandas\_libs\index.pyx", line 822, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
KeyError: 'cropped'
******************************
```

### Version information:

```Shell
Cell-ACDC version: 1.4.1rc2.dev23+g4db2d65
```

**Comment by ElpadoCan** [comment]
Hi Alissa,

For some reason something is wrong with the file ending with `dataPrepROI_coords.csv`. Could you please upload that file here? Thanks!

**Comment by ElpadoCan** [comment]
Hi Alissa, I just pushed a fix for this. Can you please update your Cell-ACDC version with `git pull` command and let me know if it works? Thank you very much!
