### ISSUE TITLE
Error when trying to combine channel-wise tifs with "Re-structure image files" tool

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#396]
### Description:

I have three tif files of dimensions (6,56,2500,2500) which is (ch, t, y, x).
I place them in one folder, then use "Re-structure image files", select an empty folder to store the results, but when I start the process, I get an error, that I attached here. 

### Terminal output:

```Shell
Scanning files...
Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\__init__.py", line 341, in inner_function
    result = func(self, *args)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\_main.py", line 1426, in workerCritical
    raise error
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\workers.py", line 43, in run
    func(self)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\workers.py", line 2190, in run
    load._restructure_multi_files_multi_pos(
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\load.py", line 2394, in _restructure_multi_files_multi_pos
    n_splits_exp, n_splits_pos = sorted_n_splits[-2:]
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\__init__.py", line 341, in inner_function
    result = func(self, *args)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\_main.py", line 1426, in workerCritical
    raise error
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\workers.py", line 43, in run
    func(self)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\workers.py", line 2190, in run
    load._restructure_multi_files_multi_pos(
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\load.py", line 2394, in _restructure_multi_files_multi_pos
    n_splits_exp, n_splits_pos = sorted_n_splits[-2:]
ValueError: not enough values to unpack (expected 2, got 1)
```

### Version information:

```Shell
Using Qt 5.15.2 with Python 3.9.16
Welcome to Cell-ACDC v1.4.1rc6.dev24+g24aaccf.d20230818
```

**Comment by ElpadoCan** [comment]
Hi Beno, what are you trying to achieve? Is each file a single experiment? Because at the moment the only two structures supported are `Multiple files, one for each time-point`, and `Multiple files, one for each channel`. Neither of these seems to cover your case because you have the channels in one single file, right?

**Comment by Beno71** [comment]
Will be solved with custom parsing function, thanks!
