### ISSUE TITLE
Unable to restart ACDC, error " 'numpy._DTypeMeta' object is not subscriptable"

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#410]
### Description:

I tried to run the segmentation module with Yeaz v2, but the Yeaz installation failed apparently so I was told to do it manually and restart CellACDC. When I try to reopen cellACDC in my acdc conda environment, I get the error below. I tried updating to v1.4.7 (from 1.4.5), but it turned out the same. I haven't seen this kind of startup error before.

### Way to reproduce:

Not sure how to reproduce because I can no longer open ACDC to get to the segmentation module...

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jyxiao\anaconda3\envs\acdc\Scripts\cellacdc.exe\__main__.py", line 7, in <module>
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 49, in run
    run_gui()
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 97, in run_gui
    app, splashScreen = _run._setup_app(splashscreen=True)
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\_run.py", line 274, in _setup_app
    from . import load
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cellacdc\load.py", line 6, in <module>
    import cv2
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\jyxiao\anaconda3\envs\acdc\lib\site-packages\cv2\typing\__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

### Version information:

```Shell
CellACDC v1.4.5 or 1.4.7
Python 3.9.6
```

**Comment by jordanyx** [comment]
Nevermind! It turns out the failed installation of YeaZ messed up my numpy package somehow, I fixed it by upgrading the 'numba' package, then installing yeaz manually instead of within cellacdc.

**Comment by ElpadoCan** [comment]
Ah, interesting I will keep an eye on it, but huge thanks for providing a fix already!
