### ISSUE TITLE
Trying to install delta2 segmentation model automatically causes a fatal error

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#433]
### Description:

Trying to install delta2 segmentation model automatically causes a fatal error

### Way to reproduce:

Trying to install delta2 segmentation model automatically

### Terminal output:

```Shell
Downloading delta (if needed)...
Importing delta...
Traceback (most recent call last):
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\models\delta\__init__.py", line 22, in <module>
    import delta
ModuleNotFoundError: No module named 'delta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\myutils.py", line 2138, in import_segment_module
    acdcSegment = import_module(f'cellacdc.models.{model_name}.acdcSegment')
  File "C:\Users\SchmollerLab\.pyenv\pyenv-win\versions\3.9.13\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\models\delta\__init__.py", line 55, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: User aborted delta installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\_main.py", line 1517, in launchSegm
    self.segmWin.main()
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\segm.py", line 475, in main
    acdcSegment = myutils.import_segment_module(model_name)
  File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\myutils.py", line 2143, in import_segment_module
    model_path = cp[model_name]['path']
  File "C:\Users\SchmollerLab\.pyenv\pyenv-win\versions\3.9.13\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'delta'
```

### Version information:

```Shell
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Cell-ACDC version: 0.1.dev2385+gd646793.d20231110 (which should be up to date with current main)
```

**Comment by ElpadoCan** [comment]
Hi Timon, I pushed a possible fix for this, let me know if it works, thank you very much!
