### ISSUE TITLE
Fata error after selecting not to align images again

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#434]
### Description:

Error after selecting not to align images again

### Way to reproduce:

Selecting Module "Segmentation and tracking", afterwards going through the process and choosing to set a ROI, which will open a data prep window. Then choosing not to align images again.

### Terminal output:

```Shell
Traceback (most recent call last):
File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\__init__.py", line 363, in inner_function
result = func(self, *args)
File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\dataPrep.py", line 1749, in prepData
success = self.alignData(self.user_ch_name, posData)
File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\dataPrep.py", line 2064, in alignData
self.startAlignDataWorker(posData, align, user_ch_name)
File "C:\Users\SchmollerLab\CellACDC_symmtrack\Cell_ACDC\cellacdc\dataPrep.py", line 1660, in startAlignDataWorker
self.progressWin.show(self.app)
AttributeError: 'dataPrepWin' object has no attribute 'app'
```

### Version information:

```Shell
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Cell-ACDC version: 0.1.dev2385+gd646793.d20231110 (which should be up to date with current main)
```

**Comment by ElpadoCan** [comment]
Hi Timon, I pushed a possible fix for this. To test it, pull the last version and let me know if it works, thanks!
