### ISSUE TITLE
Critical error on using brush 

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#458]
```shell
 Traceback (most recent call last):
 File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\__init__.py", line 365, in inner_function
 result = func(self, *args, **kwargs)
 File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\gui.py", line 20157, in updateAllImages
 self.setImageImg2()
 File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\gui.py", line 19073, in setImageImg2
 allDelIDs, DelROIlab = self.getDelROIlab()
 File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\gui.py", line 9753, in getDelROIlab
 DelROIlab = self.get_2Dlab(posData.lab, force_z=False).copy()
 AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by ElpadoCan** [comment]
At the moment we cannot replicate this error
