### ISSUE TITLE
Error in opening folder for segmentation

### ISSUE THREAD

**Issue by NidhiChopdekar** [SchmollerLab/Cell_ACDC#511]
### Description:

Hello,
After I try to launch the GUI and try to open my positions folder, it asks me for the channel name. I am not exactly sure what I must provide but my dataset has a channel w-50 in its name, so i just put that (have tried other channels as well) but i end up getting an error saying 

Error in function _openFolder. Traceback (most recent call last):
File "C:\Users\Nidhi\anaconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 403, in inner_function
result = func(self, *args, **kwargs)
File "C:\Users\Nidhi\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 22765, in _openFolder
self.gui_createOverlayColors()
File "C:\Users\Nidhi\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 4192, in gui_createOverlayColors
self.overlayColors[ch] = self.overlayRGBs[c]
IndexError: list index out of range

Please help me out

Thanks
Nidhi

[.2024-04-21_03-10-42_acdc_gui_0a706c29-7d3c-42d0-8581-82da1de9d6a1_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/15051002/default.2024-04-21_03-10-42_acdc_gui_0a706c29-7d3c-42d0-8581-82da1de9d6a1_stdout.log)

**Comment by ElpadoCan** [comment]
Hi Nidhi, 

I'm sorry to hear you are having this issue, but we will fix it. 

It sounds like Cell-ACDC wants to load more than 12 additional channels, but I'm guessing you do not have that many, right? 

Could you please send me a screenshot of the files you have in the `Experiment_folder/Position_1` folder? Thanks! 

Best,
Francesco

**Comment by ElpadoCan** [comment]
I just realised that the tif files ends with `t050` suggesting that you have one tif file per time point? That will not work in acdc, you will need to concatenate the tiff files into a single file with all the time points. You will need one tif file per channel.

You can convert the files into acdc-compatible structure with module `0. Create data structure from microscopy/image files(s)...`. You will then choose `Re-structure image files` and follow the wizard. Let me know if it works thanks

Best
Francesco
