### ISSUE TITLE
Loading other position of same file (Shift+P) in dataprep bug

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#540]
### Description:

I think that when you cancel "Load other position (Shift+P)" in dataprep, it causes an error when you later try to use this functionality again.

### Way to reproduce:

Multiple positions of timelapse data, open dataprep, open other position from there, cancel, try to open other position from there again. Nothing happens but you get this non-critical error in the terminal

### Terminal output:

```Shell
Traceback (most recent call last):████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/it]
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\dataPrep.py", line 2508, in openRecentFile
    self.openFolder(exp_path=path)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\dataPrep.py", line 2625, in openFolder
    self.loadFiles(exp_path, user_ch_file_paths, user_ch_name)
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\dataPrep.py", line 2476, in loadFiles
    self.stopAutomaticLoadingPos()
  File "C:\Users\mairhoermann\Documents\phd-code\Cell_ACDC\cellacdc\dataPrep.py", line 480, in stopAutomaticLoadingPos
    if self.AutoPilot.timer.isActive():
AttributeError: 'AutoPilot' object has no attribute 'timer'
```

### Version information:

```Shell
Windows-10-10.0.19045-SP0
Cell-ACDC version: 1.4.32.dev153+g7297e5b.d20240718
```

**Comment by ElpadoCan** [comment]
Hi @Beno71, I just tried to replicate this with Cell-ACDC `1.3.2.dev34+g466bc0f03` and I could not replicate. It can well be that it has been fixed along the way. 

For now, I'm closing the issue, but if this happens again feel free to re-open it. 

Thank you for your contributions!
