### ISSUE TITLE
ERROR Manual bud seperation tool

### ISSUE THREAD

**Issue by AlissaFinster** [SchmollerLab/Cell_ACDC#552]
### Description:

As soon as I want to use the manual bud seperation tool and click on a cell, ACDC goes into error state and reports this: 
"Error in function gui_mousePressEventImg2.

Traceback (most recent call last):
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\__init__.py", line 405, in inner_function
result = func(self, *args)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 4807, in gui_mousePressEventImg2
lab2D, success = self.auto_separate_bud_ID(
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11507, in auto_separate_bud_ID
cnt, defects = self.convexity_defects(lab_ID_bool, eps_percent)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11491, in convexity_defects
defects = cv2.convexityDefects(cnt,hull) # see https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.html
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\convhull.cpp:360: error: (-5:Bad argument) The convex hull indices are not monotonous, which can be in the case when the input contour contains self-intersections in function 'cv::convexityDefects'
"

### Terminal output:

```Shell
Traceback (most recent call last):
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\__init__.py", line 405, in inner_function
result = func(self, *args)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 4807, in gui_mousePressEventImg2
lab2D, success = self.auto_separate_bud_ID(
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11507, in auto_separate_bud_ID
cnt, defects = self.convexity_defects(lab_ID_bool, eps_percent)
File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11491, in convexity_defects
defects = cv2.convexityDefects(cnt,hull) # see https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.html
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\convhull.cpp:360: error: (-5:Bad argument) The convex hull indices are not monotonous, which can be in the case when the input contour contains self-intersections in function 'cv::convexityDefects'
```

### Log file:

19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Initialized log file "C:\Users\alissa.finster\acdc-appdata\.acdc-logs\2024-09-19_09-07-55_acdc_gui_da028733-53bb-43cc-9860-9c5ebbf31fcb_stdout.log" ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Running Python v3.10.12 from "C:\Users\alissa.finster\Miniconda3\envs\acdc" ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Using Qt version 6.5.2 ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Cell-ACDC installation directory: "C:\Users\alissa.finster\Cell_ACDC\cellacdc" ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ System version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)] ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Platform: Windows-10-10.0.19042-SP0 ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Initializing GUI v1.4.32.dev10+gc292f159 ------------------------  19-09-2024, 09:07:55 - cellacdc-logger-acdc_gui - INFO: ------------------------ Initiliazing profilers... ------------------------  19-09-2024, 09:07:57 - cellacdc-logger-acdc_gui - INFO: ------------------------ GUI ready. ------------------------  19-09-2024, 09:07:59 - cellacdc-logger-acdc_gui - INFO: ------------------------ Asking to select a folder path... ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loading from E:/20240807/Position_37 ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Using .npz aligned file (E:/20240807\Position_37\Images\AF_20240807_s37_Dia_Ph3_aligned.npz)... ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Number of TIFF files detected: 0 ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Reading Dia_Ph3 channel metadata... ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Lazy loader paused. ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Lazy loader paused. ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Closing lazy loader... ------------------------  19-09-2024, 09:08:01 - cellacdc-logger-acdc_gui - INFO: ------------------------ Closing lazy loader... ------------------------  19-09-2024, 09:08:05 - cellacdc-logger-acdc_gui - INFO: ------------------------ Segmentation filename: E:/20240807\Position_37\Images\AF_20240807_s37_segm.npz ------------------------  19-09-2024, 09:08:10 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loading Position_37\Images\AF_20240807_s37_Dia_Ph3_aligned.npz... ------------------------  19-09-2024, 09:08:10 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loading Position_37\Images\AF_20240807_s37_Dia_Ph3_aligned.npz... ------------------------  19-09-2024, 09:08:10 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loaded paths: Segmentation file name: AF_20240807_s37_segm.npz ACDC output file name AF_20240807_s37_acdc_output.csv ------------------------  19-09-2024, 09:08:10 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loaded paths: Segmentation file name: AF_20240807_s37_segm.npz ACDC output file name AF_20240807_s37_acdc_output.csv ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Full dataset shape = Not Loaded ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Full dataset shape = Not Loaded ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loaded dataset shape = (341, 584, 756) ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Loaded dataset shape = (341, 584, 756) ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Number of frames = 341 ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Number of frames = 341 ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Number of z-slices per frame = 1 ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Number of z-slices per frame = 1 ------------------------  19-09-2024, 09:08:15 - cellacdc-logger-acdc_gui - INFO: ------------------------ Counting total number of segmented objects... ------------------------  19-09-2024, 09:08:16 - cellacdc-logger-acdc_gui - INFO: ------------------------ Creating graphical items... ------------------------  19-09-2024, 09:08:16 - cellacdc-logger-acdc_gui - INFO: ------------------------ ---------------------------------------------------------------------------------------------------- Files present in the first Position folder loaded:    - AF_20240807_s37_acdc_output.csv   - AF_20240807_s37_align_shift.npy   - AF_20240807_s37_custom_combine_metrics.ini   - AF_20240807_s37_dataPrepROIs_coords.csv   - AF_20240807_s37_dataPrep_bkgrROIs.json   - AF_20240807_s37_Dia_Ph3.tif   - AF_20240807_s37_Dia_Ph3_aligned.npz   - AF_20240807_s37_Dia_Ph3_aligned_bkgrRoiData.npz   - AF_20240807_s37_last_tracked_i.txt   - AF_20240807_s37_metadata.csv   - AF_20240807_s37_metadataXML.txt   - AF_20240807_s37_segm.npz   - recovery ---------------------------------------------------------------------------------------------------- ------------------------  19-09-2024, 09:08:18 - cellacdc-logger-acdc_gui - INFO: ------------------------ Initializing measurements... ------------------------  19-09-2024, 09:08:18 - cellacdc-logger-acdc_gui - INFO: ------------------------ Position_37 || Basename: AF_20240807_s37_ || Segmented channel: Dia_Ph3_aligned || Segmentation file name: segm.npz ------------------------  19-09-2024, 09:08:18 - cellacdc-logger-acdc_gui - INFO: ------------------------ Autosaving worker started. ------------------------  19-09-2024, 09:08:34 - cellacdc-logger-acdc_gui - ERROR: ------------------------ Traceback (most recent call last):   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\__init__.py", line 405, in inner_function     result = func(self, *args)   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 4807, in gui_mousePressEventImg2     lab2D, success = self.auto_separate_bud_ID(   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11507, in auto_separate_bud_ID     cnt, defects = self.convexity_defects(lab_ID_bool, eps_percent)   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11491, in convexity_defects     defects = cv2.convexityDefects(cnt,hull) # see https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.html cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\convhull.cpp:360: error: (-5:Bad argument) The convex hull indices are not monotonous, which can be in the case when the input contour contains self-intersections in function 'cv::convexityDefects'   ------------------------ Traceback (most recent call last):   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\__init__.py", line 405, in inner_function     result = func(self, *args)   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 4807, in gui_mousePressEventImg2     lab2D, success = self.auto_separate_bud_ID(   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11507, in auto_separate_bud_ID     cnt, defects = self.convexity_defects(lab_ID_bool, eps_percent)   File "C:\Users\alissa.finster\Cell_ACDC\cellacdc\gui.py", line 11491, in convexity_defects     defects = cv2.convexityDefects(cnt,hull) # see https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.html cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\convhull.cpp:360: error: (-5:Bad argument) The convex hull indices are not monotonous, which can be in the case when the input contour contains self-intersections in function 'cv::convexityDefects'  19-09-2024, 09:08:34 - cellacdc-logger-acdc_gui - INFO: ------------------------ **************************************************************************************************** WARNING: Cell-ACDC is in error state. Please, restart. **************************************************************************************************** ------------------------  19-09-2024, 09:12:52 - cellacdc-logger-acdc_gui - INFO: ------------------------ Opening log file "C:\Users\alissa.finster\acdc-appdata\.acdc-logs\2024-09-19_09-07-55_acdc_gui_da028733-53bb-43cc-9860-9c5ebbf31fcb_stdout.log"... ------------------------

### Version information:

```Shell
import' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ElpadoCan** [comment]
Hi Alissa, the error hints at a very peculiar shape of the object you are trying to separate. Does this happen with any object? If not I will need the data to test, could you please share it with me with any cloud service you prefer? Also, let me know which frame and object I should test, thanks!

**Comment by AlissaFinster** [comment]
Hi Francesco,
So actually, I think it was only an error due to one special cell. After trying the tool on another cell, it was working fine. So maybe it was just very confused by this special cell. Sorry for opening the error, but I didn't know its not general & I thought it might be interesting for you too maybe.

________________________________

**Comment by ElpadoCan** [comment]
Ok if it happens again please send me the data for me to replicate it thanks! I will close the issue for now, thanks!
