### ISSUE TITLE
Error when saving in GUI

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#56]
An error I haven't seen before when trying to save masks edited in the GUI.

**To Reproduce**
1. Open segmented movie
2. Try any save function (shortcut, menu save, etc.)
3. Get error

**Expected behavior**
Normal save behavior.

**Screenshots**
After attempting to save, the mask for the last frame got messed up as seen below:
![error pt1](https://user-images.githubusercontent.com/99368623/172977373-bb73c1f4-4892-4d33-b656-20b7d99c36a8.PNG)

This is the error window:
![error pt2](https://user-images.githubusercontent.com/99368623/172977375-a4c4bd17-ef89-4e73-955e-079ddc30ded7.PNG)

Error text copy-pasted:
"""

Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'is_history_known'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 905, in run
    acdc_df = load.pd_bool_to_int(acdc_df, inplace=False)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\load.py", line 144, in pd_bool_to_int
    isInt = pd.api.types.is_integer_dtype(acdc_df[col])
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'is_history_known'

"""

**Desktop (please complete the following information):**
 - Python version: Python 3.9.6
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc25

**Comment by jordanyx** [comment]
This appears to be working now, thanks!
