### ISSUE TITLE
Download and test with timelapse example fails

### ISSUE THREAD

**Issue by bentaculum** [SchmollerLab/Cell_ACDC#564]
### Description:

Hi ACDC,
I'm trying out acdc on my laptop, and getting the following issue.

I am on MacOS and the main branch, and get the following error when I press "Download and test with timelapse example":

```
┌─(acdc)[gallusse][SV-90M-006][~]
└─▪ cellacdc
Launching application...
Loading configuration files...
Initialized log file "/Users/gallusse/acdc-appdata/.acdc-logs/2024-10-05_14-06-26_main_04f5933b-ae9c-4087-85dc-a78dd0eca990_stdout.log"
Running Python v3.10.13 from "/Users/gallusse/miniforge3/envs/acdc"
Cell-ACDC installation directory: "/Users/gallusse/miniforge3/envs/acdc/lib/python3.10/site-packages/cellacdc"
System version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
Platform: macOS-14.3-arm64-arm-64bit
Using Qt version 5.15.8
**********************************************
Welcome to Cell-ACDC v1.4.32.dev262+ga001b7c
**********************************************
----------------------------------------------
NOTE: If application is not visible, it is probably minimized
or behind some other open windows.
----------------------------------------------
Opening GUI...
Initialized log file "/Users/gallusse/acdc-appdata/.acdc-logs/2024-10-05_14-06-30_acdc_gui_c3528199-6221-4c4b-a084-737a16f88b1f_stdout.log"
Running Python v3.10.13 from "/Users/gallusse/miniforge3/envs/acdc"
Cell-ACDC installation directory: "/Users/gallusse/miniforge3/envs/acdc/lib/python3.10/site-packages/cellacdc"
System version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
Platform: macOS-14.3-arm64-arm-64bit
Using Qt version 5.15.8
Initializing GUI v1.4.32.dev262+ga001b7c
Initiliazing profilers...
GUI ready.
Traceback (most recent call last):
  File "/Users/gallusse/miniforge3/envs/acdc/lib/python3.10/site-packages/cellacdc/help/welcome.py", line 963, in openGUIexample
    self.openGUIfolder(self.worker.exp_path)
  File "/Users/gallusse/miniforge3/envs/acdc/lib/python3.10/site-packages/cellacdc/help/welcome.py", line 900, in openGUIfolder
    self.mainWin.guiWin.openFolder(exp_path=exp_path)
AttributeError: 'mainWin' object has no attribute 'guiWin'. Did you mean: 'guiWins'?
```

### Version information:

```Shell
3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
/Users/gallusse/miniforge3/envs/acdc
macOS-14.3-arm64-arm-64bit
Cell-ACDC version: 1.4.32.dev262+ga001b7c
```
```

**Comment by ElpadoCan** [comment]
Hi @bentaculum, thanks for reporting this. I just fixed it. Please, pull the last version and let me know if it works, thank you very much! 

Best,
Francesco
