### ISSUE TITLE
Bug eraser 

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#95]
Traceback (most recent call last):File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\myutils.py", line 47, in inner_function
result = func(self, *args, **kwargs)
File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\gui.py", line 13850, in updateALLimg
self.setTempImg1Eraser(None, init=self.isSegm3D)
File "c:\users\ge29nek\desktop\cellacdc\cell_acdc\cellacdc\gui.py", line 13237, in setTempImg1Eraser
erasedRp = skimage.measure.regionprops(self.erasesedLab)
AttributeError: 'guiWin' object has no attribute 'erasesedLab'

**Comment by ElpadoCan** [comment]
Fixed
